### ISSUE TITLE
Alignment in cpio archive

### ISSUE THREAD

**Issue by jm--** [SEL4PROJ/libcpio#1]
### Intro:

I run into a problem when I try to use libcpio. It could be me not using it correctly, but after reviewing the source code, I think there might be an issue worth fixing anyway(?)
### What I'm doing:

I'm experimenting with sel4test-manifest (experimental branch) modifying the test-driver application. The Makefile for my test app contains:

```
OFILES := archive.o

COMPONENTS := file1.txt file2.txt
COMPONENTS_FULL := $(addprefix $(SOURCE_DIR)/, $(COMPONENTS))

archive.o: $(COMPONENTS_FULL)
    $(Q)mkdir -p $(dir $@)
    ${COMMON_PATH}/files_to_obj.sh $@ _cpio_archive $^
```

This works in that the archive gets built and included. file1.txt contains "ABCDEF" and file2.txt contains "1234567890". I'm building for IA32 and using gcc version 4.8.4.
### The problem:

The code that traverses the cpio headers only works correctly when `_cpio_archive` is 4-byte aligned, I think. (This is not by design, right?)

In my concrete case:

> $ nm images/myimage-ia32-pc99 | grep _cpio_archive  
> 080719fa D _cpio_archive

And 0x080719fa is not a multiple of 4. The problem manifests itself when I try to use cpio_get_file() to read the files: I can only access the first file in the cpio archive and cannot read the first two bytes of the file.
### Details:

Function cpio_parse_header() in libcpio/src/cpio.c traverses the cpio header and calls function align_up() to 4-byte align various pointers because the data structure that is "baked into" the cpio file consists of 4-byte aligned sub-parts. (This built-in alignment is with respect to the beginning of the cpio file.)

I think the problem with the libcpio code is in the call to align_up(), which includes a pointer (variable "archive") to the location of the cpio file in memory. As a consequence, the calculated alignment depends on the location of `_cpio_archive` and is only correct when it is a multiple of 4.

My current fix is to replace in function cpio_parse_header() in libcpio/src/cpio.c

```
    *data = (void *)align_up(((unsigned long)archive)
            + sizeof(struct cpio_header) + filename_length, CPIO_ALIGNMENT);

    *next = (struct cpio_header *)align_up(((unsigned long)*data) + filesize, CPIO_ALIGNMENT);
```

with

```
     unsigned long data_offset = align_up(sizeof(struct cpio_header) +
            filename_length, CPIO_ALIGNMENT);
    *data = (void *) archive + data_offset;
    *next = (void *) archive + align_up(data_offset + filesize, CPIO_ALIGNMENT);
```

Only offset values within the cpio file are considered for the alignment calculation. The pointer to the start ("archive") is added outside of align_up().
### Testing:

I tested different cpio files containing some combinations of files (different filename lengths and file sizes). And I hacked the loader script in "files_to_obj.sh" to explicitly force odd alignments of `_cpio_archive`. For example: `<snip> ._archive_cpio  : ALIGN(4) { . = (. +3); ${SYMBOL} = (.) <snip>`  

BTW: If the described issue is for real, then setting the alignment in said loader script could be a workaround to fix the issue without touching any C code.

Sorry for this long post. I hope everything I said is correct and this is helpful.
(I probably miss something, for I can't possibly be the first one who stumbles across this?)

**Comment by AdrianDanis** [comment]
Thanks for the investigative work @jm-- 
I would not be surprised if this was just an oversight in the design and it was just assumed that things would be 4 byte aligned.
Given this I think the best solution is to just fix the alignment in "files_to_obj.sh"

**Comment by jm--** [comment]
Cool! Let me know in case you want me to submit a PR.

**Comment by AdrianDanis** [comment]
I know it's trivial, but could you submit one? I have been unable to find the time to do / test this myself. I will get around to it eventually though
